// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrRAZsIICCMqp08c4PKNfQ30ROQKLf38',
    appId: '1:979684319326:web:8bfa5d3f753affc0a6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    authDomain: 'heritageaskets.firebaseapp.com',
    storageBucket: 'heritageaskets.appspot.com',
    measurementId: 'G-9FGL278PT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Ws-wCbL7r_Z4trfXwXm7mRc9ZQg7wdY',
    appId: '1:979684319326:android:421cf79af4205217a6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    storageBucket: 'heritageaskets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdVMKFBZhovBhKq47dkVNEzS-RhGEGXE',
    appId: '1:979684319326:ios:475ffd06aefec86ca6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    storageBucket: 'heritageaskets.appspot.com',
    iosBundleId: 'heritage.kologsoft.jona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmdVMKFBZhovBhKq47dkVNEzS-RhGEGXE',
    appId: '1:979684319326:ios:475ffd06aefec86ca6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    storageBucket: 'heritageaskets.appspot.com',
    iosBundleId: 'heritage.kologsoft.jona',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLrRAZsIICCMqp08c4PKNfQ30ROQKLf38',
    appId: '1:979684319326:web:2084ce0e1d668359a6d4cf',
    messagingSenderId: '979684319326',
    projectId: 'heritageaskets',
    authDomain: 'heritageaskets.firebaseapp.com',
    storageBucket: 'heritageaskets.appspot.com',
    measurementId: 'G-1Y9NNJVEQZ',
  );

}